### PR TITLE
About Page and Footer

### PR DESCRIPTION
**Pull request by jbh14**
- working nav in "header" to navigate between About Page and Home
- About page with our pitch, architecture + deployment diagrams, and cards for us
- footer with some text

### CODE REVIEW

**Review by superhermione — CHANGES_REQUESTED** [review]
Hey, Brendan! Your "About Page" is quite impressive and informative! It visually showcases all the core tech features we have.  It also matches well with our app style! Well done! I only have two minor suggestions. 
1. 
image
I suggest to center the foot note and maybe have the Disclaimer message below the copyright or you can add it into the about page as part of the introduction. I know that you have the footnote styled as a centered module, but somehow, it is starting from the bottom left and is not extended to the center. Please double check if it is centered on your local. 
In the corresponding styling file, it has an syntax error as shown in the attached screenshot. This might be the cause. 
image

2. In your about.js, there are some elements not being used. I suggest you to delete them for the cleaning up purpose. 
image

Otherwise, great work! We are getting there!

**Review by dscottd7 — CHANGES_REQUESTED** [review]
@jbh14 – Overall this is great. Nice job.

There are a few things I recommend changing:

1. Semantically, your H1 should come before any H2, which would mean that the "Make smarter decisions ..." header would go at the top of the page. Not only would that be semantically better for screen readers and webcrawlers, I think it would be better for anyone reading the page to get the tagline first, then the explanation. Stylistically, I would remove the italics – I don't think you need it.
2. For the `<Grid>` component in AboutPage.js, I would suggest this for the gutter: `<Grid gutter={{ base: 20, xs: 40, md: 60, xl: 80 }}>`
3. Footer text might look a little more subtle if you use the "dimmed" color prop: `<Text c="dimmed" size="sm" fw={500} pl="20px" >`
4. Same "dimmed" color prop might be good for the "Quibble Architecture" and "Backend Deployment to Google Cloud Run" texts since these are more like captions
5. You may also want to add a `<Space h={25} />` component after the `<Stack>` component that contains "Backend Deployment to Google Cloud Run" so that it's not so cramped on mobile with the right-hand column content that flows below it.

**Comment by jbh14** [comment]
Great feedback @superhermione !  I incorporated both suggestions and committed.

**Review by superhermione — DISMISSED** [review]
This looks great!

**Comment by jbh14** [comment]
Great suggestions @dscottd7  - I implemented all of these.

As for putting the "Make smarter decisions" tagline below the "Why/How/What" bullets, that was an intentional choice I made - when designing the poster, I like the idea of "leading" the reader to the conclusion of what Quibble does so to speak.  But given that this appeared above the "Why/How/What" in the final poster, which is also fine by me, I followed your lead to match here.

**Review by dscottd7 — APPROVED** [review]
Thanks for making those changes. Looks good.

**Pull request merged**
