### PR TITLE
Improve Comparison Title Handling, Fix Sidebar Display and Fix Restart Comparison 

### PR DESCRIPTION
**Pull request by superhermione**
This PR enhances the functionality of saving and displaying comparison titles in the comparison history sidebar. The following updates have been made:

Title Extraction Improvement: The title is now correctly extracted from the comparison content using a more flexible regular expression.
Comparison History Sidebar Updates:
The sidebar now displays the proper comparison title.
Corrected the onSelect button logic to ensure the right comparison content (item.data) is loaded when selected.
Comparison content box updates:  New Comparison button is working now.

### CODE REVIEW

**Comment by dscottd7** [comment]
As far as the functionality goes, it looks like the saving and retrieving of comparisons is working again, which is good.

When I run this code, the comparisons are saved in the sidebar, but there is often not a title saved in the sidebar. 

Perhaps this is not worth worrying about here because we will need to do it differently once we integrate with Edward's structured response anyway, which will have a specific data element for title.

------

As far as the code goes, there are a few issues:

One, I think you can remove these two constants, which you don't actually use in a meaningful way:

```
const [comparison, setComparison] = useState('');
const [error, setError] = useState('');
```

You can also remove the `setError('');` line below because you never use the `error` constant anywhere:

```
  // Reset the form and state to their initial values
  const resetForm = () => {
    setUrls(initialUrlsState);
    setPreferences(initialPreferencesState);
    setStatus({
      isProcessing: false,
      currentStep: '',
      progressPercentage: 0,
      error: '',
      comparison: ''
    });
    setError('');
  };
```
-----

Two, I don't think putting the ComparisonHistorySidebar component in App.js is an architectural choice that scales well beyond this being a single page app. I think that component belongs to the HomPage, not the entire app. The reason being, if we create another page for this app, perhaps an About page, we then have to write logic into App.js to show or hide the ComparisonHistorySidebar component with the HomePage component. That should just come as part of the HomePage component.

-----

Three, I'm not sure why you aren't using Mantine components. That is the component library we decided to use. One issue here is that the way you've implemented the sidebar, it's not responsive and looks broken on mobile. If you used Mantine components for this, it would be much simpler to make this sidebar responsive. If we accept this code as is, someone is going to have to refactor it to use Mantine components.

-----

Lastly, you don't want to commit your `.env` file to GitHub. If `.gitignore` is not stopping that file from being uploaded, you should update `.gitignore` to make sure that it does ignore your `.env` file.

**Review by dscottd7 — CHANGES_REQUESTED** [review]
My full comments are here: https://github.com/dscottd7/quibble-frontend/pull/13#issuecomment-2480818375

At minimum, I think you should remove the unused state variables and ensure your .env file is not uploaded to GitHub.

If you don't want to do the Mantine refactoring, someone else can do that after this code gets merged.

**Comment by superhermione** [comment]
> My full comments are here: [#13 (comment)](https://github.com/dscottd7/quibble-frontend/pull/13#issuecomment-2480818375)
> 
> At minimum, I think you should remove the unused state variables and ensure your .env file is not uploaded to GitHub.
> 
> If you don't want to do the Mantine refactoring, someone else can do that after this code gets merged.

1. "You can also remove the setError(''); line below because you never use the error constant anywhere:"  
    --- This was set by Edward which I thought this is our standard practice. Maybe this should have been addressed a while ago. I can of course remove it. 
3. "Lastly, you don't want to commit your .env file to GitHub. If .gitignore is not stopping that file from being uploaded, you should update .gitignore to make sure that it does ignore your .env file."
   --- Brendan committed the .env when he created this branch on Thursday night. I believe he was trying to help. You can check the commit history. I never committed ".env". 
5. I can look into other changes, especially app.js. The reason I added "ComparisonHistorySidebar" in the app.js is because the sidebar was treated as an independent element rather then a component in the homepage based on my understanding from our last meeting, especially from the design you made.
image
In addition, for real world web development, we always avoid clutter and the homepage is cluttered. In a sense, we should set up elements in modules and assemble them together. I can for sure to take out the "compareHistory" logic out of app.js to make it cleaner, and potentially modularize the homepage.  
6. For Mantine, I tried last night. It changed the look completely and was not as organized as the current look. I can take a look again if I have time. 
7. The title is saved on my end. I wonder if it's a system issue. But I agree that we will need to adapt to Edward's structured comparison logic anyway. 
image

**Comment by dscottd7** [comment]
> > My full comments are here: [#13 (comment)](https://github.com/dscottd7/quibble-frontend/pull/13#issuecomment-2480818375)
> > At minimum, I think you should remove the unused state variables and ensure your .env file is not uploaded to GitHub.
> > If you don't want to do the Mantine refactoring, someone else can do that after this code gets merged.
> 
> 1. "You can also remove the setError(''); line below because you never use the error constant anywhere:"
>    --- This was set by Edward which I thought this is our standard practice. Maybe this should have been addressed a while ago. I can of course remove it.
> 2. "Lastly, you don't want to commit your .env file to GitHub. If .gitignore is not stopping that file from being uploaded, you should update .gitignore to make sure that it does ignore your .env file."
>    --- Brendan committed the .env when he created this branch on Thursday night. I believe he was trying to help. You can check the commit history. I never committed ".env".
> 3. I can look into other changes, especially app.js. The reason I added "ComparisonHistorySidebar" in the app.js is because the sidebar was treated as an independent element rather then a component in the homepage based on my understanding from our last meeting, especially from the design you made.
>    image
>    In addition, for real world web development, we always avoid clutter and the homepage is cluttered. In a sense, we should set up elements in modules and assemble them together. I can for sure to take out the "compareHistory" logic out of app.js to make it cleaner, and potentially modularize the homepage.
> 4. For Mantine, I tried last night. It changed the look completely and was not as organized as the current look. I can take a look again if I have time.
> 5. The title is saved on my end. I wonder if it's a system issue. But I agree that we will need to adapt to Edward's structured comparison logic anyway.
>    image

@superhermione – My review of the code is precisely that – a review of the code I am looking it. It is not a critique of you personally, so please don't take it that way. I am giving feedback on all of the contributions that have gone into the pull request we are considering for inclusion in our app. It's not "your" code or "my" code or "Brendan's" code – it's our shared code. It makes no substantive difference who wrote it or when it was written. My suggestions here are for changes I believe we should make to this particular state of the code we are considering for inclusion. We don't need to blame anyone for anything – we just need to make it better. We're all responsible for the code as a team.

With respect to the ComparisonHistorySidebar, what the designs are intending to show is that there is a Header, which spans the entire top of the screen. It includes the Title of the app and the Menu for the app. Below it are the contents of the page we are looking at. In the case of the HomePage, that includes the Title of the page, Form for the URLs, and the Sidebar for past comparisons. If we change the page we are looking at, the Header should remain, but the contents of the page should change, including the Form and the Sidebar. This is a pretty standard pattern in web apps.

We used to have a Header with the app Title and Menu that spanned the top of the app, but somewhere along the way we lost that. The Menu has disappeared completely, and now the Sidebar is a top-level component alongside the Header, which on mobile means that it takes over the page. Again, not blaming a person here, but we have moved away from the design and the previously implementation of the design. The current state of the code in this PR doesn't really follow important aspects of the design, like the hierarchy and nesting of components (especially so that they work responsively) and the use of a consistent component library. Perhaps the diagram below will make the intention of the design's hierarchy more explicit:

Screenshot 2024-11-17 at 9 36 53 AM

With respect to Mantine, yes, it will change the look. That's the point – to bring consistency to the design. But it's important to apply the components with an overall app architecture and component hierarchy that are aligned. In the current state of the code in this PR, those are things we need to improve, which is why I'm trying to point them out.

**Comment by superhermione** [comment]
@dscottd7 
I appreciate your feedback and understand that the code we’re working on is shared, and it's inevitable to change each other's code. I agree that we should avoid assigning blame or ownership. However, I felt that some of your comments directed at me, like the use of "you" in reference to commits or decisions, created some confusion. So I suggest we can keep it professional in PR review to reference specific effort so that the relevant developer can stay in loop.  Like you said, we’re all contributing to the same goal, and I’d like to ensure that our communication reflects that spirit of collaboration.

I just modified code and structure based on the review. @dscottd7 @jbh14 @edwmai Please take a thorough look: 
https://github.com/dscottd7/quibble-frontend/pull/13/commits/726b23cdb5de89d768a0cf6c6f870da98dace275
image

Key Changes:

1. Comparison History Sidebar Enhancements: AddedMantine component and accessible user URLSs. 

2. Improved Layout for Comparison Data: Display comparison content alongside product URLs.

3. Enhanced Data Saving Logic: Added a hook ComparisonHistoryManager to manage all the comparison history-related functionality in the app. 

4. Code Refactoring: Restructured App.js to focus on layout and main component rendering;
                                 Improved component clarity by consolidating core app functionality using MainContent.js. 

5. Removed Redundant State Variables: Cleaned up unused logic set up before. 

6. Added "Hamburger" button back to header.

**Pull request merged**
